config/routes.rb
Geoinfotour::Application.routes.draw do
  devise_for :users

  root :to => redirect('/' + I18n::t('url_routing.destinations') + '/')

  sections = ['destinations', 'routes', 'events', 'terms', 'personalities']
  sections.each do |section|
    match("#{section}/" => "#{section}#index",
          :defaults => { :category_name => "#{section}"}, :via => :get)
    match("#{section}/:id" => "#{section}#show",
          :constraints => {:id => /\d+/}, :via => :get)
    match("#{section}/:id/publish" => "#{section}#publish",
          :constraints => {:id => /\d+/}, :via => :post, :as => "publish_#{section.singularize}")
    match("#{section}/:id/unpublish" => "#{section}#unpublish",
          :constraints => {:id => /\d+/}, :via => :post, :as => "unpublish_#{section.singularize}")
    match "#{section}/new" => "#{section}#new", :via => :get
    match "#{section}/drafts" => "#{section}#drafts", :via => :get
    match "#{section}/:category_name" => "#{section}#index", :via => :get
    resources section
  end

  resources 'pages'

  sections.each do |section|
    match(I18n::t("url_routing.#{section}") + '/' => "#{section}#index",
          :defaults => { :category_name => "#{section}"}, :via => :get)
    match("#{I18n::t 'url_routing.' + section}/:id(/:title)" => "#{section}#show",
          :constraints => {:id => /\d+/}, :via => :get)
    match "#{I18n::t 'url_routing.' + section}/:category_name" => "#{section}#index", :via => :get
  end

  match("#{I18n::t("url_routing.maps")}/" => "maps#index", :via => :get)
  match("#{I18n::t("url_routing.maps")}/markers" => "maps#markers", :via => :get)

  match("#{I18n::t("url_routing.about")}/" => "about#index", :via => :get)
  match("#{I18n::t("url_routing.about")}/edit" => "about#edit", :via => :get)

  match("#{I18n::t("url_routing.sitemap")}/" => "sitemap#index", :via => :get)

  match("/sitemap.:format" => "xml_sitemap#index", :via => :get)

  resources :users

end

app/views/layouts/application.html.haml
!!!html
%html{:lang => 'cz'}
  %head
    %meta{:charset => 'utf-8'}
    %title
      - if @doc.present?
        = "#{@doc.title} | egeon.cz"
      - elsif current_section
        = "#{t current_section.name} | egeon.cz"
      - else
        = "egeon.cz"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    %link{ :href => "https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css", :rel => "stylesheet" }
    %link{ :href => "https://unpkg.com/leaflet@1.9.2/dist/leaflet.css", :integrity => "sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14=", :crossorigin => "", :rel => "stylesheet" }
    %link{ :href => "https://unpkg.com/leaflet.markercluster@1.1.0/dist/MarkerCluster.css", :rel => "stylesheet" }
    %link{ :href => "https://unpkg.com/leaflet.markercluster@1.1.0/dist/MarkerCluster.Default.css", :rel => "stylesheet" }
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
  %body
    .navbar
      .navbar-inner
        .container-fluid
          = link_to image_tag("/icons/egeon_logo.png", border: 0, :width => 40, :height => 40), '/', class: 'brand'

          %ul.nav
            - index = 0
            - Category.root.each do |c|
              - active = "active" if current_section == c
              - if index == 0
                - border_style_class = "nav-border-left"
              - else
                - border_style_class = "nav-border-inner"
              %li{ :class => "#{active} main-menu nav-border-common #{border_style_class}" }
                = link_to t(c.name), "/#{t 'url_routing.' + c.name}/", { :rel => c.name }
              - index += 1
            %li.main-menu.nav-border-common.nav-border-inner= link_to t(:maps), "/#{t 'url_routing.maps'}/"
            %li.main-menu.nav-border-common.nav-border-inner= link_to t(:sitemap), "/#{t 'url_routing.sitemap'}/"
            %li.main-menu.nav-border-common.nav-border-right= link_to t(:about), "/#{t 'url_routing.about'}/"

          %ul.nav.pull-right
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{ "data-toggle" => "dropdown", :href =>"#"}
                  = t(:actions)
                  %b.caret
                %ul.dropdown-menu
                  - if current_section
                    %li= link_to t(:new_document), "/#{current_section.name}/new", { :id => :new_document}
                    - if action_name == 'show'
                      %li= link_to t(:edit_document), "/#{current_section.name}/#{@doc.id}/edit", :rel => 'edit'
                    - if ['show', 'edit'].include? action_name
                      %li= link_to t(:delete_document), "/#{current_section.name}/#{@doc.id}/", :method => :delete, :confirm => t(:deletion_confirmation, :title => @doc.title), :rel => 'delete'
                      %li.hidden= button_to "delete document", "/#{current_section.name}/#{@doc.id}/", :method => :delete, :form => {:name => "delete_document"}
                      - if @doc.draft?
                        %li= link_to t(:publish), polymorphic_path([:publish, @doc]), :method => :post, :rel => 'publish'
                      - else
                        %li= link_to t(:unpublish), polymorphic_path([:unpublish, @doc]), :method => :post, :rel => 'unpublish'
                    %li= link_to t(:list_drafts), "/#{current_section.name}/drafts", { :rel => 'drafts' }
                  - if controller.controller_name == 'about' && action_name == 'index'
                    %li= link_to t(:edit_about), about_edit_path
              %li.dropdown
                %a.dropdown-toggle{ "data-toggle" => "dropdown", :href =>"#"}
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t(:log_out), destroy_user_session_path, :method => :delete, :rel => 'logout'
            - else
              %li.dropdown
                %a.dropdown-toggle{ "data-toggle" => "dropdown", :href =>"#"}
                  = t(:actions)
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t(:login), new_user_session_path

    - if controller_name != 'maps'
      .main_page_header
        - if controller_name == 'routes'
          .text-center
            .icon-menu
              %nav
              %ul
                %li
                  %a{ :href => "/trasy/routes-for-walkers/"}
                    %img{ :src => '/icons/routes-for-walkers.png', :title => t(:go_to_category_routes_for_walkers)}
                %li
                  %a{ :href => "/trasy/city-sightseeing/"}
                    %img{ :src => '/icons/city-sightseeing.png', :title => t(:go_to_category_city_sightseeing)}
                %li
                  %a{ :href => "/trasy/biking/"}
                    %img{ :src => '/icons/biking.png', :title => t(:go_to_category_biking)}
                %li
                  %a{ :href => "/trasy/cross-country-skiing/"}
                    %img{ :src => '/icons/cross-country-skiing.png', :title => t(:go_to_category_cross_country_skiing)}
                %li
                  %a{ :href => "/trasy/waterman-routes/"}
                    %img{ :src => '/icons/waterman-routes.png', :title => t(:go_to_category_waterman_routes)}

        - if controller_name == 'destinations'
          .text-center
            .icon-menu
              %nav
                %ul
                  %li
                    %a{ :href => "/cile/informace/"}
                      %img{ :src => '/icons/informace.png', :title => t(:go_to_category_informace)}
                  %li
                    %a{ :href => "/cile/ubytovani/"}
                      %img{ :src => '/icons/ubytovani.png', :title => t(:go_to_category_ubytovani)}
                  %li
                    %a{ :href => "/cile/sluzby-pro-cyklisty/"}
                      %img{ :src => '/icons/sluzby-pro-cyklisty.png', :title => t(:go_to_category_cyklo)}
                  %li
                    %a{ :href => "/cile/sidla/"}
                      %img{ :src => '/icons/sidla.png', :title => t(:go_to_category_sidla)}
                  %li
                    %a{ :href => "/cile/priroda/"}
                      %img{ :src => '/icons/priroda.png', :title => t(:go_to_category_priroda)}
                  %li
                    %a{ :href => "/cile/pamatky/"}
                      %img{ :src => '/icons/pamatky.png', :title => t(:go_to_category_pamatky)}
                  %li
                    %a{ :href => "/cile/koupani/"}
                      %img{ :src => '/icons/koupani.png', :title => t(:go_to_category_koupani)}
                  %li
                    %a{ :href => "/cile/ostatni/"}
                      %img{ :src => '/icons/ostatni.png', :title => t(:go_to_category_ostatni)}

      - if @breadcrumbs.present?
        .breadcrumbs-box
          .container-fluid
            .text-left
              %nav#breadcrumbs
                %ul.breadcrumb
                  %li= t(:breadcrumbs)
                  - @breadcrumbs.each do |b|
                    - last = (b == @breadcrumbs.last)
                    %li{ :class => "#{'active' if last}" }
                      - title = (b.class == Category) ? t(b.name) : b.name
                      = link_to title, category_path(b), :class => b.name
                    - unless last
                      %span.divider /
          %hr.hr

    - if controller_name == "maps"
      .minimal-content-margin
        = yield
    - elsif controller_name == "about"
      .container-fluid
        = yield
    - else
      .container-fluid
        .row-fluid
          #sidebar.span3
            .minimal-content-margin
              -# Search box
              - if current_section
                .search
                  %form
                    %input#search{ :type => 'text', :name => 'q', :value => params[:q], :placeholder => t(:search)}

              -# Category navigation box
              - if @current_category.present?
                %nav#categories-pane
                  %ul.nav.nav-list
                    - if params[:id].present?
                      %li.nav-header= t(:back)
                      %li= link_to t(@current_category.name), category_path(@current_category)
                    - elsif not @current_category.root?
                      %li.nav-header= t(:back)
                      - parent = @current_category.parent
                      %li= link_to t(parent.name), category_path(parent)

                    %li.nav-header= t(:categories)
                    - if @current_category.children.present?
                      - @current_category.children.each do |c|
                        %li.child= link_to t(c.name), category_path(c), :class => c.path.map(&:name).join(' '), :rel => c.name
                    - else
                      %li= t(:no_categories)

          #content.span9
            .minimal-content-margin
              - if notice.present?
                %p.alert.alert-info.alert-block= notice
              - if alert.present?
                %p.alert.alert-block= alert
              - if flash[:error].present?
                %p.alert.alert-error.alert-block= flash[:error]

              - if controller_name == "terms" && action_name == "index"
                %ul.terms_tags_navbar
                  - @filter_tags.each do |tag|
                    %li
                      = link_to tag, {:controller => "terms", :action => "index", :filter_tag => tag }
                    \-
                  %li
                    = link_to t(:remove_filter), {:controller => "terms", :action => "index"}

              - if current_section && action_name == 'index' && @documents.blank?
                %p.not-found= t(:no_documents_found)
              = yield
    %footer
      .container-fluid
        %p= t(:copyright_notice)
        %p!= t(:this_program_is_free_software)

    = javascript_include_tag "application"
    = yield :scripts
    %script{ :src => "https://unpkg.com/leaflet@1.9.2/dist/leaflet.js", :integrity=> "sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg=", :crossorigin => "" }
    %script{ :src => "https://unpkg.com/leaflet.markercluster@1.1.0/dist/leaflet.markercluster.js", :crossorigin => "" }
    %script{ :src => "https://polyfill.io/v3/polyfill.min.js?features=default" }